USE RetailOpsLab;
GO

CREATE TABLE app.Users
(
    UserId INT IDENTITY(1,1) CONSTRAINT PK_Users PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL CONSTRAINT UQ_Users_UserName UNIQUE,
    FullName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(200) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
    CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE app.Roles
(
    RoleId INT IDENTITY(1,1) CONSTRAINT PK_Roles PRIMARY KEY,
    RoleName NVARCHAR(100) NOT NULL CONSTRAINT UQ_Roles_RoleName UNIQUE
);
GO

CREATE TABLE app.UserRoles
(
    UserId INT NOT NULL,
    RoleId INT NOT NULL,
    AssignedAt DATETIME2(0) NOT NULL CONSTRAINT DF_UserRoles_AssignedAt DEFAULT SYSUTCDATETIME(),

    CONSTRAINT PK_UserRoles PRIMARY KEY (UserId, RoleId),
    CONSTRAINT FK_UserRoles_Users FOREIGN KEY (UserId) REFERENCES app.Users(UserId),
    CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleId) REFERENCES app.Roles(RoleId)
);
GO
