USE RetailOpsLab;
GO

CREATE TABLE audit.AuditLogs
(
    AuditLogId BIGINT IDENTITY(1,1) CONSTRAINT PK_AuditLogs PRIMARY KEY,
    AppUserId INT NULL,
    ActionName NVARCHAR(100) NOT NULL,
    SchemaName NVARCHAR(100) NOT NULL,
    TableName NVARCHAR(100) NOT NULL,
    RecordId NVARCHAR(100) NULL,
    OldValue NVARCHAR(MAX) NULL,
    NewValue NVARCHAR(MAX) NULL,
    SqlUserName NVARCHAR(200) NOT NULL CONSTRAINT DF_AuditLogs_SqlUserName DEFAULT SUSER_SNAME(),
    HostName NVARCHAR(200) NULL CONSTRAINT DF_AuditLogs_HostName DEFAULT HOST_NAME(),
    CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_AuditLogs_CreatedAt DEFAULT SYSUTCDATETIME(),

    CONSTRAINT FK_AuditLogs_Users FOREIGN KEY (AppUserId) REFERENCES app.Users(UserId)
);
GO

CREATE TABLE audit.BlockedActions
(
    BlockedActionId BIGINT IDENTITY(1,1) CONSTRAINT PK_BlockedActions PRIMARY KEY,
    AppUserId INT NULL,
    ActionName NVARCHAR(100) NOT NULL,
    Reason NVARCHAR(300) NOT NULL,
    SqlUserName NVARCHAR(200) NOT NULL CONSTRAINT DF_BlockedActions_SqlUserName DEFAULT SUSER_SNAME(),
    HostName NVARCHAR(200) NULL CONSTRAINT DF_BlockedActions_HostName DEFAULT HOST_NAME(),
    CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_BlockedActions_CreatedAt DEFAULT SYSUTCDATETIME()
);
GO
